# Generated by Django 2.0 on 2020-03-29 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGateway',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('rssi', models.IntegerField(db_column='rssi', default=0)),
                ('rssitb', models.IntegerField(db_column='rssitb', default=0)),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 9, 9, 14, 56836))),
            ],
            options={
                'db_table': 'datagateway',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DevicesGateway',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.TextField(blank=True, db_column='device_name')),
                ('device_description', models.TextField(db_column='device_description', default='')),
                ('registration_time', models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 9, 9, 14, 56836))),
            ],
            options={
                'db_table': 'devicesgateway',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='rssi',
            field=models.IntegerField(db_column='rssi', default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 9, 9, 14, 56836)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_description',
            field=models.TextField(db_column='device_description', default=''),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_name',
            field=models.TextField(blank=True, db_column='device_name'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 9, 9, 14, 56836)),
        ),
        migrations.AddField(
            model_name='datagateway',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ble.Devices'),
        ),
    ]
