# Generated by Django 2.0 on 2020-03-29 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0002_auto_20200329_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 16, 50, 36, 401614)),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ble.DevicesGateway'),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 16, 50, 36, 417241)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 16, 50, 36, 401614)),
        ),
        migrations.AlterField(
            model_name='devicesgateway',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 16, 50, 36, 401614)),
        ),
    ]
