# Generated by Django 2.0 on 2020-03-29 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0003_auto_20200329_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 16, 55, 41, 704249)),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='rssi',
            field=models.FloatField(db_column='rssi', default=0),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='rssitb',
            field=models.FloatField(db_column='rssitb', default=0),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 3, 29, 16, 55, 41, 704249)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 16, 55, 41, 704249)),
        ),
        migrations.AlterField(
            model_name='devicesgateway',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 3, 29, 16, 55, 41, 704249)),
        ),
    ]
