# Generated by Django 2.0 on 2020-04-22 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0004_auto_20200329_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagateway',
            name='deltaA',
            field=models.FloatField(db_column='deltaA', default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 4, 22, 17, 30, 12, 72038)),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 4, 22, 17, 30, 12, 75036)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 4, 22, 17, 30, 12, 71038)),
        ),
        migrations.AlterField(
            model_name='devicesgateway',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 4, 22, 17, 30, 12, 73036)),
        ),
    ]
