# Generated by Django 2.0 on 2020-04-22 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0006_auto_20200422_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 4, 22, 17, 31, 58, 249209)),
        ),
        migrations.AlterField(
            model_name='datagateway',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2020, 4, 22, 17, 31, 58, 251208)),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 4, 22, 17, 31, 58, 249209)),
        ),
        migrations.AlterField(
            model_name='devicesgateway',
            name='registration_time',
            field=models.DateTimeField(db_column='registration_time', default=datetime.datetime(2020, 4, 22, 17, 31, 58, 250209)),
        ),
    ]
